### ISSUE TITLE
Key issue 

### ISSUE THREAD

**Issue by TechNaWolf** [alec-hs/Flaxs-Arma-Server-Tool#42]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Steam server2\armafiles\keys\asrai3.bikey'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at FAST.MainWindow.CopyKeys(String modID)
   at FAST.MainWindow.VB$StateMachine_47_RunSteamCommand.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by alec-hs** [comment]
Thanks for this and the other issues, I'll take a look at them this weekend.
