### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by TechNaWolf** [alec-hs/Flaxs-Arma-Server-Tool#43]
Was making a vanilla test server to make sure it would run saved the profile then hit launch then received this error

`System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FAST.NewServerTab.LaunchServer()
   at FAST.NewServerTab.LaunchServer_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by TechNaWolf** [comment]
Im not sure if missed something in the documentation or nor but the reason the error accured was because the steam cmd didnt actually download arma on the stable branch

**Comment by alec-hs** [comment]
Will add exception handling for this in 2.0
