### ISSUE TITLE
Program crash while downloading 2 mods 

### ISSUE THREAD

**Issue by 0xlord** [alec-hs/Flaxs-Arma-Server-Tool#51]
`System.ArgumentException: Illegal characters in path.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at FAST.MainWindow.CopyKeys(String modID)
   at FAST.MainWindow.VB$StateMachine_47_RunSteamCommand.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

https://steamcommunity.com/sharedfiles/filedetails/?id=909547724
https://steamcommunity.com/workshop/filedetails/?id=520618345

Windows Server 2016
Run with Admin privilege

**Comment by alec-hs** [comment]
Fixed in FAST2 - will not be fixed in FAST.
