### ISSUE TITLE
Flaxs Error Report

### ISSUE THREAD

**Issue by ATEX0R** [alec-hs/Flaxs-Arma-Server-Tool#54]
Hellou i today upload new mods and flaxs crash.... 

System.InvalidCastException: Conversion from string "Not Installed" to type 'Date' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
   at FAST.MainWindow.UpdateAllMods_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

this is error report ;)

**Comment by alec-hs** [comment]
Fixed in FAST2 - https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2
