### ISSUE TITLE
First time install fail to install mods. Got vcredist and .net

### ISSUE THREAD

**Issue by Manish-Yadav-Git** [alec-hs/Flaxs-Arma-Server-Tool#55]
Could not find path, possibly an administrator/privileges issue. DUMP:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Server\keys\ace_3.12.3.36.bikey'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at FAST.MainWindow.CopyKeys(String modID)
   at FAST.MainWindow.VB$StateMachine_47_RunSteamCommand.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by alec-hs** [comment]
Please use FAST 2

https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2
