### ISSUE TITLE
Can't Download Steam Content

### ISSUE THREAD

**Issue by NaxBFM** [alec-hs/Flaxs-Arma-Server-Tool#56]
I'm getting this code whenever I try to download something from steam. This has been tested on different systems as well.

System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at FAST.ImportMod.ImportModToList(String modUrl)
   at FAST.ImportMod.ImportButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam

**Comment by alec-hs** [comment]
Hi can you upload your user.config - it is found in:

\AppData\Local\KestrelStudios\FAST2.exe_Url_4beg40pslclvprin43ax53amko3bhcmo\2.0.0.0\

**Comment by alec-hs** [comment]
Fixed in [FAST2](https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2)
