### ISSUE TITLE
Updated two mods, and then got the error

### ISSUE THREAD

**Issue by Blueduckraider50** [alec-hs/Flaxs-Arma-Server-Tool#59]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\SteamCmd\8G#N\steamapps\workshop\content\107410\861133494'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at FAST.MainWindow.CopyKeys(String modID)
   at FAST.MainWindow.VB$StateMachine_47_RunSteamCommand.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Blueduckraider50** [comment]
Nvm. I messed up directory without noticing.
